
###
GET http://localhost:8000/learning/sync HTTP/1.1

###

GET http://localhost:8000/learning/sync HTTP/1.1

###

POST http://localhost:8000/learning/ask HTTP/1.1

{"question": "how to generate access token?"}

###